redirectUri: projet4A
clientId: ZDeTdvPpIW9d0cDIUVxiX3tHmjMD4WMdMQ5dP_KH1FT8IU7i6tuSYiHhCU-3brEX
clientAccessToken: fPx66qMCI3hIUZILQqOPV16c7wQboAStDOHAEtcxEyGJaPr9uCdPFLK7ERuQpVNK
baseParisURL: https://opendata.paris.fr/api/records/1.0/search/
parisWifi: ?dataset=paris-wi-fi-utilisation-des-hotspots-paris-wi-fi